name: kafka-rest-sdk-go
lang: go
semaphore:
  enable: true
  pipeline_enable: false
  tasks:
    - name: git tag
      branch: git-tag
      pipeline_file: .semaphore/git-tag.yml
      parameters:
        - name: TAG
          required: true
          description: The name of the tag to be created.
