/*
 * Kafka HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// MirrorLag struct for MirrorLag
type MirrorLag struct {
	Partition int32 `json:"partition"`
	Lag       int64 `json:"lag"`
}
