/*
 * Kafka HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// AlterConfigBatchRequestDataData struct for AlterConfigBatchRequestDataData
type AlterConfigBatchRequestDataData struct {
	Name      string  `json:"name"`
	Value     *string `json:"value,omitempty"`
	Operation *string `json:"operation,omitempty"`
}
