/*
 * REST Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

import (
	"time"
)

// LicenseData struct for LicenseData
type LicenseData struct {
	Kind              string           `json:"kind"`
	Metadata          ResourceMetadata `json:"metadata"`
	ClusterId         string           `json:"cluster_id"`
	Category          string           `json:"category"`
	CategoryShortName string           `json:"category_short_name"`
	LicenseType       string           `json:"license_type"`
	// Absent when the license does not expire (e.g., the built-in Developer / Free-Forever license).
	ExpiresAt  time.Time `json:"expires_at,omitempty"`
	Audience   string    `json:"audience,omitempty"`
	LicenseJwt string    `json:"license_jwt"`
	Status     string    `json:"status"`
	// Internal Kafka topic the license is stored in. Absent when not applicable.
	TopicName string `json:"topic_name,omitempty"`
}
