/*
 * Kafka HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// BrokerShutdownStatus the model 'BrokerShutdownStatus'
type BrokerShutdownStatus string

// List of BrokerShutdownStatus
const (
	BROKERSHUTDOWNSTATUS_ERROR     BrokerShutdownStatus = "ERROR"
	BROKERSHUTDOWNSTATUS_CANCELED  BrokerShutdownStatus = "CANCELED"
	BROKERSHUTDOWNSTATUS_PENDING   BrokerShutdownStatus = "PENDING"
	BROKERSHUTDOWNSTATUS_COMPLETED BrokerShutdownStatus = "COMPLETED"
)
