/*
 * REST Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// ShareGroupDataAllOf struct for ShareGroupDataAllOf
type ShareGroupDataAllOf struct {
	ClusterId    string       `json:"cluster_id"`
	ShareGroupId string       `json:"share_group_id"`
	State        string       `json:"state"`
	Coordinator  Relationship `json:"coordinator"`
	Consumers    Relationship `json:"consumers"`
	// Number of consumers in this share group
	ConsumerCount int32 `json:"consumer_count"`
	// Total number of partitions assigned to this share group across all consumers
	PartitionCount int32 `json:"partition_count"`
	// List of topic-partitions assigned to this share group, including those from empty groups
	AssignedTopicPartitions []ShareGroupTopicPartitionData `json:"assigned_topic_partitions,omitempty"`
}
