/*
 * Kafka HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// ReplicaStatusData struct for ReplicaStatusData
type ReplicaStatusData struct {
	Kind               string           `json:"kind"`
	Metadata           ResourceMetadata `json:"metadata"`
	ClusterId          string `json:"cluster_id"`
	TopicName          string `json:"topic_name"`
	BrokerId           int32  `json:"broker_id"`
	PartitionId        int32  `json:"partition_id"`
	Leader             bool   `json:"is_leader"`
	Observer           bool   `json:"is_observer"`
	IsrEligible        bool   `json:"is_isr_eligible"`
	InIsr              bool   `json:"is_in_isr"`
	CaughtUp           bool   `json:"is_caught_up"`
	LogStartOffset     int32  `json:"log_start_offset"`
	LogEndOffset       int32  `json:"log_end_offset"`
	LastCaughtUpTimeMs int32  `json:"last_caught_up_time_ms"`
	LastFetchTimeMs    int32  `json:"last_fetch_time_ms"`
	LinkName           string `json:"link_name,omitempty"`
}
