// Copyright 2021 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * REST Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// ListMirrorTopicsResponseDataAllOf struct for ListMirrorTopicsResponseDataAllOf
type ListMirrorTopicsResponseDataAllOf struct {
	LinkName        string            `json:"link_name"`
	MirrorTopicName string            `json:"mirror_topic_name"`
	SourceTopicName string            `json:"source_topic_name"`
	NumPartitions   int32             `json:"num_partitions"`
	MirrorLags      []MirrorLag       `json:"mirror_lags"`
	MirrorStatus    MirrorTopicStatus `json:"mirror_status"`
	StateTimeMs     int64             `json:"state_time_ms"`
}
