/*
 * Kafka HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// BrokerConfigDataAllOf struct for BrokerConfigDataAllOf
type BrokerConfigDataAllOf struct {
	BrokerId int32 `json:"broker_id"`
}
