/*
 * REST Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// ChangeReplicationFactorBatchRequestData struct for ChangeReplicationFactorBatchRequestData
type ChangeReplicationFactorBatchRequestData struct {
	Data []ChangeReplicationFactorRequestData `json:"data"`
	// The time in milliseconds to wait for the request to complete. Default: 60000
	TimeoutMs *int32 `json:"timeout_ms,omitempty"`
}
