/*
 * REST Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// AlterBrokerHealthData struct for AlterBrokerHealthData
type AlterBrokerHealthData struct {
	ClusterId    string `json:"cluster_id"`
	BrokerId     int32  `json:"broker_id"`
	Component    string `json:"component"`
	HealthStatus string `json:"health_status"`
}
