/*
 * REST Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// ReplicationFactorChangeAction the model 'ReplicationFactorChangeAction'
type ReplicationFactorChangeAction string

// List of ReplicationFactorChangeAction
const (
	REPLICATIONFACTORCHANGEACTION_REPLICATION_FACTOR_CHANGE ReplicationFactorChangeAction = "REPLICATION_FACTOR_CHANGE"
	REPLICATIONFACTORCHANGEACTION_CANCELLATION              ReplicationFactorChangeAction = "CANCELLATION"
	REPLICATIONFACTORCHANGEACTION_UNKNOWN                   ReplicationFactorChangeAction = "UNKNOWN"
)
