/*
 * Kafka HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3
// TopicDataAllOf struct for TopicDataAllOf
type TopicDataAllOf struct {
	ClusterId string `json:"cluster_id"`
	TopicName string `json:"topic_name"`
	IsInternal bool `json:"is_internal"`
	ReplicationFactor int32 `json:"replication_factor"`
	Partitions Relationship `json:"partitions"`
	Configs Relationship `json:"configs"`
	PartitionReassignments Relationship `json:"partition_reassignments"`
}
