/*
 * Kafka HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3
// CreateTopicRequestDataConfigs struct for CreateTopicRequestDataConfigs
type CreateTopicRequestDataConfigs struct {
	Name string `json:"name"`
	Value *string `json:"value,omitempty"`
}
