/*
 * REST Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

import (
	"time"
)

// ProduceBatchRequestEntry struct for ProduceBatchRequestEntry
type ProduceBatchRequestEntry struct {
	// Batch entry ID.
	Id          string                 `json:"id"`
	PartitionId *int32                 `json:"partition_id,omitempty"`
	Headers     []ProduceRequestHeader `json:"headers,omitempty"`
	Key         *ProduceRequestData    `json:"key,omitempty"`
	Value       *ProduceRequestData    `json:"value,omitempty"`
	Timestamp   *time.Time             `json:"timestamp,omitempty"`
}
