/*
 * Kafka HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3
// CreateTopicRequestData struct for CreateTopicRequestData
type CreateTopicRequestData struct {
	TopicName string `json:"topic_name"`
	PartitionsCount int32 `json:"partitions_count"`
	ReplicationFactor int32 `json:"replication_factor"`
	Configs []CreateTopicRequestDataConfigs `json:"configs,omitempty"`
}
