/*
 * REST Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// ShareGroupTopicPartitionDataAllOf struct for ShareGroupTopicPartitionDataAllOf
type ShareGroupTopicPartitionDataAllOf struct {
	// The name of the topic
	TopicName string `json:"topic_name"`
	// The partition ID
	PartitionId int32        `json:"partition_id"`
	Partition   Relationship `json:"partition"`
}
