/*
 * REST Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

import (
	"time"
)

// ProduceResponse struct for ProduceResponse
type ProduceResponse struct {
	ErrorCode   int32                `json:"error_code"`
	Message     string               `json:"message,omitempty"`
	ClusterId   string               `json:"cluster_id,omitempty"`
	TopicName   string               `json:"topic_name,omitempty"`
	PartitionId int32                `json:"partition_id,omitempty"`
	Offset      int64                `json:"offset,omitempty"`
	Timestamp   *time.Time           `json:"timestamp,omitempty"`
	Key         *ProduceResponseData `json:"key,omitempty"`
	Value       *ProduceResponseData `json:"value,omitempty"`
}
