/*
 * Kafka HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3
// AlterMirrorStatusResponseDataAllOf2 struct for AlterMirrorStatusResponseDataAllOf2
type AlterMirrorStatusResponseDataAllOf2 struct {
	DestinationTopicName string `json:"destination_topic_name"`
	ErrorMessage *string `json:"error_message"`
	ErrorCode *int32 `json:"error_code"`
}
