/*
 * Kafka HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// Error struct for Error
type Error struct {
	ErrorCode int32  `json:"error_code"`
	Message   string `json:"message"`
}
