/*
 * REST Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

import (
	"time"
)

// ReplicationFactorChangeData struct for ReplicationFactorChangeData
type ReplicationFactorChangeData struct {
	Kind      string           `json:"kind"`
	Metadata  ResourceMetadata `json:"metadata"`
	ClusterId string           `json:"cluster_id"`
	TopicName string           `json:"topic_name"`
	// The desired replication factor for the topic.
	DesiredReplicationFactor int32 `json:"desired_replication_factor"`
	// Kept as the enum type rather than string, same generator caveat as Status below.
	Action ReplicationFactorChangeAction `json:"action"`
	// Kept as the enum type rather than string: a `make gen` run currently
	// mistypes this as string due to an openapi-generator property-name
	// collision with unrelated inline "status" enums elsewhere in the spec.
	Status ReplicationFactorChangeStatus `json:"status"`
	// The date and time at which this Replication Factor Change was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time at which this Replication Factor Change was last updated.
	UpdatedAt    time.Time    `json:"updated_at"`
	ErrorCode    *int32       `json:"error_code,omitempty"`
	ErrorMessage *string      `json:"error_message,omitempty"`
	Topic        Relationship `json:"topic"`
}
