/*
 * REST Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// CellDataAllOf struct for CellDataAllOf
type CellDataAllOf struct {
	Kind                    string           `json:"kind"`
	Metadata                ResourceMetadata `json:"metadata"`
	CellId                  int32            `json:"cell_id"`
	State                   int32            `json:"state"`
	Brokers                 []int32          `json:"brokers"`
	OpenForTenantAssignment bool             `json:"open_for_tenant_assignment"`
}
