/*
 * REST Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3

// CellConfigData struct for CellConfigData
type CellConfigData struct {
	ClusterId    string          `json:"cluster_id"`
	Cells        []CellDataAllOf `json:"cells"`
	CellsEnabled bool            `json:"cells_enabled"`
	ErrorCode    *int32          `json:"error_code,omitempty"`
	ErrorMessage *string         `json:"error_message,omitempty"`
}
