/*
 * Kafka HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kafkarestv3
// ConsumerGroupState the model 'ConsumerGroupState'
type ConsumerGroupState string

// List of ConsumerGroupState
const (
	CONSUMERGROUPSTATE_UNKNOWN ConsumerGroupState = "UNKNOWN"
	CONSUMERGROUPSTATE_PREPARING_REBALANCE ConsumerGroupState = "PREPARING_REBALANCE"
	CONSUMERGROUPSTATE_COMPLETING_REBALANCE ConsumerGroupState = "COMPLETING_REBALANCE"
	CONSUMERGROUPSTATE_STABLE ConsumerGroupState = "STABLE"
	CONSUMERGROUPSTATE_DEAD ConsumerGroupState = "DEAD"
	CONSUMERGROUPSTATE_EMPTY ConsumerGroupState = "EMPTY"
)
